name: Intel Linux Build
on:
  push
  pull_request
  workflow_dispatch
  schedule:
    - cron: '*/5 * * * *'

defaults:
  run:
    shell: bash -leo pipefail {0}

env:
  cache_key: intel2  # The number (#) following the cache_key "intel" is to flush Action cache.
  CC: icc
  FC: ifort
  CXX: icpc
  I_MPI_CC: icc
  I_MPI_F90: ifort

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-upp  # This is for getting spack.yaml
        if: steps.cache-env.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
            path: CItest

      - name: install-intel-compilers
        run: |
          echo "X${{ github.event.schedule }}X"
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update
          sudo apt-get install intel-oneapi-dev-utilities intel-oneapi-mpi-devel intel-oneapi-openmp intel-oneapi-compiler-fortran intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic
          echo "source /opt/intel/oneapi/setvars.sh" >> ~/.bash_profile

      # Install dependencies using Spack
      - name: install-dependencies-with-spack
        if: steps.cache-env.outputs.cache-hit != 'true'
        run: |
          find /home/runner/work -name CMakeLists.txt
          echo sudo mv /usr/local/ /usr_local_mv
          sudo apt install cmake
          cd CItest
          mkdir build
          cd build
          cmake ..
