name: Intel Linux Build
on: [push, pull_request, workflow_dispatch]

defaults:
  run:
    shell: bash -leo pipefail {0}

env:
  cache_key: intel2  # The number (#) following the cache_key "intel" is to flush Action cache.
  CC: icc
  FC: ifort
  CXX: icpc
  I_MPI_CC: icc
  I_MPI_F90: ifort

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-upp  # This is for getting spack.yaml
        if: steps.cache-env.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
            path: CItest

      # Install dependencies using Spack
      - name: install-dependencies-with-spack
        if: steps.cache-env.outputs.cache-hit != 'true'
        run: |
          find /home/runner/work -name CMakeLists.txt
          echo sudo mv /usr/local/ /usr_local_mv
          sudo apt install cmake
          mkdir build
          cd build
          cmake ..
